apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-audit
  template:
    metadata:
      labels:
        app: ms-audit
    spec:
      containers:
        - name: ms-audit
          image: parking/ms-audit:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: audit_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: parking-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: parking-secrets
                  key: POSTGRES_PASSWORD
            - name: JWKS_URI
              valueFrom:
                configMapKeyRef:
                  name: parking-config
                  key: JWKS_URI
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: parking-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: parking-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: parking-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: parking-secrets
                  key: RABBITMQ_PASSWORD
            - name: RABBITMQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: parking-config
                  key: RABBITMQ_EXCHANGE
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: parking-config
                  key: RABBITMQ_QUEUE
---
apiVersion: v1
kind: Service
metadata:
  name: ms-audit
spec:
  selector:
    app: ms-audit
  ports:
    - port: 3001
      targetPort: 3001
