apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parking-saas

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - rabbitmq.yaml
  - usuarios.yaml
  - zonas.yaml
  - vehiculos.yaml
  - tickets.yaml
  - audit.yaml
  - kong.yaml
  - ingress.yaml
